"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, LockKeyhole } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function RestablecerContrasenaPage() {
  const [password, setPassword] = useState(""); const [confirmacion, setConfirmacion] = useState(""); const [mensaje, setMensaje] = useState(""); const [listo, setListo] = useState(false); const [guardando, setGuardando] = useState(false);
  useEffect(() => { void supabase.auth.getSession().then(({ data }) => { setListo(Boolean(data.session)); if (!data.session) setMensaje("Abre este enlace desde el correo de restablecimiento o solicita uno nuevo al administrador."); }); }, []);
  async function guardar(event: FormEvent) { event.preventDefault(); if (password.length < 8 || password !== confirmacion) { setMensaje("Usa una contraseña de al menos 8 caracteres y confirma que coincida."); return; } setGuardando(true); const { error } = await supabase.auth.updateUser({ password }); setGuardando(false); setMensaje(error ? error.message : "Contraseña actualizada. Ya puedes volver a iniciar sesión."); }
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-5"><section className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><div className="grid size-11 place-items-center rounded-xl bg-orange-50 text-orange-600"><KeyRound/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-orange-600">Acceso seguro</p><h1 className="mt-2 text-3xl font-black">Nueva contraseña</h1><p className="mt-2 text-sm text-slate-500">Define una contraseña nueva para tu cuenta del CRM.</p><form onSubmit={guardar} className="mt-6 space-y-4"><label className="block text-sm font-bold">Nueva contraseña<div className="relative mt-1.5"><LockKeyhole className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3" disabled={!listo}/></div></label><label className="block text-sm font-bold">Confirmar contraseña<input required minLength={8} type="password" value={confirmacion} onChange={(event) => setConfirmacion(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5" disabled={!listo}/></label>{mensaje && <p className="rounded-xl bg-slate-100 p-3 text-sm text-slate-700">{mensaje}</p>}<button disabled={!listo || guardando} className="w-full rounded-xl bg-slate-950 py-3 text-sm font-bold text-white disabled:opacity-50">{guardando ? "Actualizando…" : "Guardar contraseña"}</button></form></section></main>;
}
