"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Banknote, CheckCircle2, CircleDollarSign, FileClock, FileText, Landmark, ReceiptText } from "lucide-react";
import { moneda } from "@/lib/crm";
import { supabase } from "@/lib/supabase";

type Pedido = { id: string; codigo: string | null; cliente: string | null; cliente_id: string | null; total: number | string | null; saldo_pendiente: number | string | null; pago_estado: string | null; forma_pago: string | null; fecha_pedido: string | null; fecha_entrega: string | null; estado: string | null };
type Pago = { id: string; pedido_id: string | null; monto: number | string | null; metodo: string | null; referencia: string | null; fecha: string | null; created_at: string | null };
type Factura = { id: string; pedido_id: string | null; estado: string | null; serie: string | null; numero: string | null; uuid_fel: string | null; total: number | string | null; proveedor_fel: string | null; error_fel: string | null; emitida_at: string | null; created_at: string | null };
const dinero = (valor: number | string | null | undefined) => moneda(Number(valor || 0));
const fecha = (valor: string | null) => valor ? new Intl.DateTimeFormat("es-GT", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${valor.slice(0, 10)}T12:00:00`)) : "—";
const esFacturaEmitida = (estado: string | null) => /emitida|facturada|certificada/i.test(estado || "");

export default function FinanzasPage() {
  const [pedidos, setPedidos] = useState<Pedido[]>([]); const [pagos, setPagos] = useState<Pago[]>([]); const [facturas, setFacturas] = useState<Factura[]>([]);
  const [pedidoId, setPedidoId] = useState(""); const [monto, setMonto] = useState(""); const [metodo, setMetodo] = useState("Efectivo"); const [referencia, setReferencia] = useState(""); const [fechaPago, setFechaPago] = useState(new Date().toISOString().slice(0, 10));
  const [busqueda, setBusqueda] = useState(""); const [estadoFactura, setEstadoFactura] = useState("Todos"); const [fechaInicio, setFechaInicio] = useState(""); const [fechaFin, setFechaFin] = useState("");
  const [cargando, setCargando] = useState(false); const [guardando, setGuardando] = useState(false); const [error, setError] = useState(""); const [aviso, setAviso] = useState("");

  async function cargar() {
    setCargando(true); setError("");
    const [pedidosRes, pagosRes, facturasRes] = await Promise.all([
      supabase.from("pedidos").select("id,codigo,cliente,cliente_id,total,saldo_pendiente,pago_estado,forma_pago,fecha_pedido,fecha_entrega,estado").order("fecha_pedido", { ascending: false }).limit(300),
      supabase.from("pagos").select("id,pedido_id,monto,metodo,referencia,fecha,created_at").order("created_at", { ascending: false }).limit(200),
      supabase.from("facturas").select("id,pedido_id,estado,serie,numero,uuid_fel,total,proveedor_fel,error_fel,emitida_at,created_at").order("created_at", { ascending: false }).limit(200),
    ]);
    const problema = pedidosRes.error || pagosRes.error || facturasRes.error;
    if (problema) { console.error(problema); setError("No se pudo actualizar la información financiera. Intenta de nuevo."); setCargando(false); return; }
    setPedidos((pedidosRes.data || []) as Pedido[]); setPagos((pagosRes.data || []) as Pago[]); setFacturas((facturasRes.data || []) as Factura[]); setCargando(false);
  }
  useEffect(() => { const timer = window.setTimeout(() => void cargar(), 0); return () => window.clearTimeout(timer); }, []);

  const pedidosPorId = useMemo(() => new Map(pedidos.map((pedido) => [pedido.id, pedido])), [pedidos]);
  const cuentasPendientes = useMemo(() => pedidos.filter((pedido) => Number(pedido.saldo_pendiente || 0) > 0).sort((a, b) => Number(b.saldo_pendiente || 0) - Number(a.saldo_pendiente || 0)), [pedidos]);
  const totalPendiente = cuentasPendientes.reduce((suma, pedido) => suma + Number(pedido.saldo_pendiente || 0), 0);
  const cobradoPeriodo = pagos.filter((pago) => (!fechaInicio || (pago.fecha || "") >= fechaInicio) && (!fechaFin || (pago.fecha || "") <= fechaFin)).reduce((suma, pago) => suma + Number(pago.monto || 0), 0);
  const facturaPorPedido = useMemo(() => new Map(facturas.map((factura) => [factura.pedido_id || "", factura])), [facturas]);
  const pendientesFEL = useMemo(() => pedidos.filter((pedido) => pedido.pago_estado === "Pagado" && !facturaPorPedido.has(pedido.id)), [pedidos, facturaPorPedido]);
  const facturasFiltradas = useMemo(() => facturas.filter((factura) => {
    const pedido = pedidosPorId.get(factura.pedido_id || ""); const texto = `${factura.serie || ""} ${factura.numero || ""} ${factura.uuid_fel || ""} ${pedido?.codigo || ""} ${pedido?.cliente || ""}`.toLowerCase();
    const fechaFactura = (factura.emitida_at || factura.created_at || "").slice(0, 10); const grupo = esFacturaEmitida(factura.estado) ? "Emitidas" : "Pendientes";
    return texto.includes(busqueda.toLowerCase()) && (estadoFactura === "Todos" || estadoFactura === grupo) && (!fechaInicio || fechaFactura >= fechaInicio) && (!fechaFin || fechaFactura <= fechaFin);
  }), [facturas, pedidosPorId, busqueda, estadoFactura, fechaInicio, fechaFin]);
  const pedidoSeleccionado = cuentasPendientes.find((pedido) => pedido.id === pedidoId); const saldoSeleccionado = Number(pedidoSeleccionado?.saldo_pendiente || 0);

  async function registrarPago(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setAviso(""); const valor = Number(monto);
    if (!pedidoSeleccionado || !Number.isFinite(valor) || valor <= 0) { setError("Selecciona un pedido e ingresa un monto válido."); return; }
    if (valor > saldoSeleccionado) { setError(`El abono no puede ser mayor al saldo de ${dinero(saldoSeleccionado)}.`); return; }
    setGuardando(true);
    const { error: pagoError } = await supabase.from("pagos").insert({ pedido_id: pedidoSeleccionado.id, cliente_id: pedidoSeleccionado.cliente_id, monto: valor, metodo, referencia: referencia || null, fecha: fechaPago || null });
    if (pagoError) { setError(pagoError.message); setGuardando(false); return; }
    const nuevoSaldo = Math.max(0, saldoSeleccionado - valor); const { error: pedidoError } = await supabase.from("pedidos").update({ saldo_pendiente: nuevoSaldo, pago_estado: nuevoSaldo === 0 ? "Pagado" : "Parcial", forma_pago: metodo }).eq("id", pedidoSeleccionado.id);
    if (pedidoError) { setError(`El pago fue registrado, pero no se pudo actualizar el saldo: ${pedidoError.message}`); setGuardando(false); await cargar(); return; }
    setPedidoId(""); setMonto(""); setReferencia(""); setAviso("Pago registrado y saldo actualizado."); setGuardando(false); await cargar();
  }

  return <main className="min-h-screen bg-slate-100 px-4 py-7 sm:px-7 lg:px-10"><div className="mx-auto max-w-[1600px]">
    <header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-orange-600">Tesorería y FEL</p><h1 className="mt-2 text-4xl font-black text-slate-950">Cobros y facturación</h1><p className="mt-2 text-sm text-slate-600">Registra abonos, controla saldos y revisa el estado de cada documento fiscal.</p></div><button disabled={cargando} onClick={() => void cargar()} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{cargando ? "Actualizando…" : "Actualizar"}</button></header>
    {(error || aviso) && <p className={`mb-5 rounded-xl p-4 text-sm font-semibold ${error ? "bg-rose-50 text-rose-700" : "bg-emerald-50 text-emerald-700"}`}>{error || aviso}</p>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl bg-slate-950 p-5 text-white"><Landmark size={20}/><p className="mt-4 text-xs font-bold uppercase text-slate-400">Por cobrar</p><p className="mt-2 text-3xl font-black">{dinero(totalPendiente)}</p><p className="mt-1 text-sm text-slate-400">{cuentasPendientes.length} cuentas abiertas</p></article><article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800"><CircleDollarSign size={20}/><p className="mt-4 text-xs font-bold uppercase">Cobrado en el rango</p><p className="mt-2 text-3xl font-black">{dinero(cobradoPeriodo)}</p><p className="mt-1 text-sm">{pagos.length} pagos registrados</p></article><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-800"><FileClock size={20}/><p className="mt-4 text-xs font-bold uppercase">Pendientes de facturar</p><p className="mt-2 text-3xl font-black">{pendientesFEL.length}</p><p className="mt-1 text-sm">Pagados sin documento FEL</p></article><article className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-blue-800"><CheckCircle2 size={20}/><p className="mt-4 text-xs font-bold uppercase">Facturas emitidas</p><p className="mt-2 text-3xl font-black">{facturas.filter((factura) => esFacturaEmitida(factura.estado)).length}</p><p className="mt-1 text-sm">Historial disponible</p></article></section>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_180px_180px_180px_auto]"><input value={busqueda} onChange={(event) => setBusqueda(event.target.value)} placeholder="Buscar factura, pedido o cliente" className="rounded-xl border border-slate-200 px-4 py-3 text-sm"/><select value={estadoFactura} onChange={(event) => setEstadoFactura(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option>Todos</option><option>Pendientes</option><option>Emitidas</option></select><input type="date" value={fechaInicio} onChange={(event) => setFechaInicio(event.target.value)} aria-label="Fecha desde" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><input type="date" value={fechaFin} onChange={(event) => setFechaFin(event.target.value)} aria-label="Fecha hasta" className="rounded-xl border border-slate-200 px-3 py-3 text-sm"/><button onClick={() => { setBusqueda(""); setEstadoFactura("Todos"); setFechaInicio(""); setFechaFin(""); }} className="text-sm font-bold text-slate-500 underline">Limpiar</button></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[390px_1fr]"><form onSubmit={registrarPago} className="h-fit space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><h2 className="flex items-center gap-2 text-xl font-black"><Banknote size={20}/> Registrar abono</h2><p className="mt-1 text-sm text-slate-500">El sistema calcula el saldo y marca pagos parciales o completos.</p></div><select required value={pedidoId} onChange={(event) => setPedidoId(event.target.value)} className="w-full rounded-xl border border-slate-200 p-3 text-sm"><option value="">Selecciona una cuenta por cobrar</option>{cuentasPendientes.map((pedido) => <option key={pedido.id} value={pedido.id}>{pedido.codigo || "Sin código"} · {pedido.cliente || "Sin cliente"} · {dinero(pedido.saldo_pendiente)}</option>)}</select>{pedidoSeleccionado && <div className="rounded-xl bg-slate-100 p-3 text-sm"><p className="font-bold">Saldo actual: {dinero(saldoSeleccionado)}</p><p className="mt-1 text-slate-500">Total pedido: {dinero(pedidoSeleccionado.total)} · Entrega: {fecha(pedidoSeleccionado.fecha_entrega)}</p></div>}<input required type="number" min="0.01" max={saldoSeleccionado || undefined} step="0.01" placeholder="Monto recibido" value={monto} onChange={(event) => setMonto(event.target.value)} className="w-full rounded-xl border border-slate-200 p-3"/><div className="grid grid-cols-2 gap-3"><select value={metodo} onChange={(event) => setMetodo(event.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option><option>Link de pago</option><option>POS</option></select><input type="date" value={fechaPago} onChange={(event) => setFechaPago(event.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm"/></div><input placeholder="Referencia / comprobante" value={referencia} onChange={(event) => setReferencia(event.target.value)} className="w-full rounded-xl border border-slate-200 p-3"/><button disabled={guardando} className="w-full rounded-xl bg-slate-950 p-3 font-bold text-white disabled:opacity-60">{guardando ? "Guardando…" : "Guardar pago"}</button></form>
    <div className="space-y-6"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="flex items-center gap-2 font-black"><ReceiptText size={20}/> Cuentas por cobrar</h2><p className="mt-1 text-sm text-slate-500">Saldos abiertos ordenados de mayor a menor.</p></div><p className="font-black text-orange-600">{dinero(totalPendiente)}</p></div><div className="divide-y divide-slate-100">{cuentasPendientes.slice(0, 10).map((pedido) => <Link href={`/pedidos/${pedido.id}`} key={pedido.id} className="flex items-center justify-between gap-4 p-5 hover:bg-slate-50"><div><p className="font-black text-slate-950">{pedido.codigo || "Pedido sin código"} · {pedido.cliente || "Sin cliente"}</p><p className="mt-1 text-sm text-slate-500">Entrega {fecha(pedido.fecha_entrega)} · {pedido.pago_estado || "Pendiente"}</p></div><div className="text-right"><p className="font-black text-orange-600">{dinero(pedido.saldo_pendiente)}</p><p className="mt-1 text-xs text-slate-500">de {dinero(pedido.total)}</p></div></Link>)}{!cuentasPendientes.length && <p className="p-8 text-center text-slate-500">No hay cuentas por cobrar.</p>}</div></section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-black"><FileText size={20}/> Historial de facturas FEL</h2><p className="mt-1 text-sm text-slate-500">Documentos pendientes, emitidos o con observación del certificador.</p></div><p className="text-sm font-semibold text-slate-500">{facturasFiltradas.length} documentos</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Factura / pedido</th><th className="p-4">Cliente</th><th className="p-4">Estado FEL</th><th className="p-4">Fecha</th><th className="p-4 text-right">Total</th><th className="p-4">Detalle</th></tr></thead><tbody>{facturasFiltradas.map((factura) => { const pedido = pedidosPorId.get(factura.pedido_id || ""); return <tr key={factura.id} className="border-t border-slate-100"><td className="p-4 font-semibold">{factura.serie && factura.numero ? `${factura.serie}-${factura.numero}` : pedido?.codigo || "Sin numerar"}</td><td className="p-4">{pedido?.cliente || "Cliente no disponible"}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${esFacturaEmitida(factura.estado) ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-800"}`}>{factura.estado || "Pendiente"}</span></td><td className="p-4">{fecha(factura.emitida_at || factura.created_at)}</td><td className="p-4 text-right font-black">{dinero(factura.total)}</td><td className="p-4 text-xs text-slate-500">{factura.uuid_fel || factura.error_fel || factura.proveedor_fel || "—"}</td></tr>; })}{!facturasFiltradas.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">Aún no hay facturas registradas con estos filtros.</td></tr>}</tbody></table></div></section>
    <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black text-amber-900">Pendientes de facturar</h2><p className="mt-1 text-sm text-amber-800">Estos pedidos están pagados, pero todavía no tienen un documento FEL registrado.</p><div className="mt-4 flex flex-wrap gap-2">{pendientesFEL.map((pedido) => <Link href={`/pedidos/${pedido.id}`} key={pedido.id} className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-amber-800 ring-1 ring-amber-200">{pedido.codigo || "Pedido"} · {dinero(pedido.total)}</Link>)}{!pendientesFEL.length && <p className="text-sm font-semibold text-emerald-700">No hay pedidos pagados pendientes de facturar.</p>}</div></section></div></section>
  </div></main>;
}
