import { CheckCircle2, CircleAlert, ExternalLink, ShieldCheck } from "lucide-react";

const integrations = [
  { name: "Supabase", detail: "Base de datos, permisos y eventos", status: "Configurado en entorno local", color: "text-green-700" },
  { name: "WhatsApp Business API", detail: "Conversaciones, plantillas y pedidos desde chat", status: "Requiere cuenta Meta Business y número API", color: "text-amber-700" },
  { name: "Facebook e Instagram", detail: "Mensajes, prospectos y campañas", status: "Webhook preparado; falta crear la app de Meta", color: "text-amber-700" },
  { name: "Facturación FEL", detail: "Emisión, anulación y archivos fiscales", status: "Requiere certificador y credenciales fiscales", color: "text-amber-700" },
  { name: "Vercel", detail: "Despliegue, dominios y variables de producción", status: "Pendiente de vincular el repositorio", color: "text-amber-700" },
];

export default function IntegracionesPage() {
  return <section className="space-y-8 p-6 md:p-10"><header><p className="text-sm font-bold uppercase tracking-[.2em] text-sky-600">Centro de conexiones</p><h1 className="text-4xl font-black">Integraciones</h1><p className="mt-2 max-w-3xl text-gray-500">El CRM ya separa las claves públicas de las privadas. Configura cada proveedor desde su panel y registra los secretos únicamente como variables de entorno.</p></header><div className="grid gap-4 lg:grid-cols-2">{integrations.map((integration) => <article key={integration.name} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><div className="flex gap-3"><ShieldCheck className="text-sky-600"/><div><h2 className="text-xl font-black">{integration.name}</h2><p className="mt-1 text-gray-500">{integration.detail}</p></div></div><p className={`mt-5 flex items-center gap-2 text-sm font-bold ${integration.color}`}>{integration.status.startsWith("Configurado") ? <CheckCircle2 size={17}/> : <CircleAlert size={17}/>} {integration.status}</p></article>)}</div><div className="rounded-3xl bg-slate-950 p-6 text-white"><h2 className="text-xl font-black">Pasos para activar Meta</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm text-slate-300"><li>Crea una aplicación Business en Meta Developers y agrega WhatsApp, Messenger e Instagram.</li><li>Configura <code className="text-white">/api/webhooks/meta</code> como callback y usa <code className="text-white">META_VERIFY_TOKEN</code>.</li><li>Guarda <code className="text-white">META_APP_SECRET</code>, token de acceso y número de teléfono exclusivamente en Vercel/Supabase secrets.</li><li>Ejecuta la migración CRM y valida que la firma del webhook sea aceptada.</li></ol><a className="mt-5 inline-flex items-center gap-2 font-bold text-sky-300" href="https://developers.facebook.com/docs/whatsapp/cloud-api" target="_blank" rel="noreferrer">Abrir documentación de Meta <ExternalLink size={16}/></a></div></section>;
}
