-- Clasifica la entrega sin confundirla con el importe de envío cobrado.
alter table public.pedidos
  add column if not exists entrega_mensajero boolean not null default false;

create index if not exists pedidos_entrega_mensajero_fecha_idx
  on public.pedidos (entrega_mensajero, fecha_entrega desc)
  where requiere_envio = true;

create or replace function private.registrar_pedido_completo(p_datos jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_usuario uuid := (select auth.uid()); v_cliente_id uuid := nullif(p_datos->>'cliente_id','')::uuid; v_pedido_id uuid; v_numero integer; v_codigo text; v_item jsonb; v_producto public.productos; v_subtotal numeric(14,2) := 0; v_total numeric(14,2); v_abono numeric(14,2) := greatest(coalesce((p_datos->>'abono_inicial')::numeric, 0), 0); v_costo_envio numeric(14,2) := greatest(coalesce((p_datos->>'costo_envio')::numeric, 0), 0); v_requiere_envio boolean := coalesce((p_datos->>'requiere_envio')::boolean, false); v_entrega_mensajero boolean := coalesce((p_datos->>'entrega_mensajero')::boolean, false); v_estado_pago text; v_direccion_id uuid;
begin
  if v_usuario is null or not private.tiene_modulo_crm('pedidos') then raise exception 'No autorizado para registrar pedidos'; end if;
  if trim(coalesce(p_datos->>'cliente','')) = '' then raise exception 'Ingresa el nombre del cliente'; end if;
  if jsonb_typeof(p_datos->'items') <> 'array' or jsonb_array_length(p_datos->'items') = 0 then raise exception 'Agrega al menos un producto'; end if;
  if v_requiere_envio and (trim(coalesce(p_datos->>'direccion','')) = '' or trim(coalesce(p_datos->>'departamento_entrega','')) = '' or trim(coalesce(p_datos->>'municipio_entrega','')) = '' or trim(coalesce(p_datos->>'zona_entrega','')) = '') then raise exception 'Completa dirección, departamento, municipio y zona de entrega'; end if;
  v_entrega_mensajero := v_requiere_envio and v_entrega_mensajero;
  if v_cliente_id is null then select id into v_cliente_id from public.clientes where (nullif(trim(p_datos->>'telefono'),'') is not null and telefono = trim(p_datos->>'telefono')) or (nullif(trim(p_datos->>'nit'),'') is not null and nit = trim(p_datos->>'nit')) order by updated_at desc nulls last limit 1; end if;
  if v_cliente_id is null then insert into public.clientes(nombre,telefono,email,nit,razon_social,direccion,canal_origen) values (trim(p_datos->>'cliente'), nullif(trim(p_datos->>'telefono'),''), nullif(trim(p_datos->>'correo_fiscal'),''), nullif(trim(p_datos->>'nit'),''), nullif(trim(p_datos->>'razon_social'),''), nullif(trim(p_datos->>'direccion_fiscal'),''), coalesce(nullif(trim(p_datos->>'canal_origen'),''),'Manual')) returning id into v_cliente_id; else update public.clientes set nombre=trim(p_datos->>'cliente'), telefono=nullif(trim(p_datos->>'telefono'),''), email=nullif(trim(p_datos->>'correo_fiscal'),''), nit=nullif(trim(p_datos->>'nit'),''), razon_social=nullif(trim(p_datos->>'razon_social'),''), direccion=nullif(trim(p_datos->>'direccion_fiscal'),''), updated_at=now() where id=v_cliente_id; end if;
  for v_item in select value from jsonb_array_elements(p_datos->'items') loop select * into v_producto from public.productos where id = (v_item->>'id')::uuid and estado = 'Activo'; if not found then raise exception 'Producto no disponible'; end if; if coalesce((v_item->>'cantidad')::numeric,0) <= 0 then raise exception 'Cantidad inválida'; end if; v_subtotal := v_subtotal + round(coalesce((v_item->>'precio')::numeric, v_producto.precio_venta) * (v_item->>'cantidad')::numeric, 2); end loop;
  v_total := v_subtotal + case when v_requiere_envio then v_costo_envio else 0 end; if v_abono > v_total then raise exception 'El abono no puede superar el total'; end if; v_estado_pago := case when v_abono >= v_total and v_total > 0 then 'Pagado' when v_abono > 0 then 'Pago parcial' else 'Pendiente' end;
  insert into public.pedidos(cliente_id,cliente,telefono,direccion,fecha_pedido,fecha_entrega,estado,pago_estado,estado_pago,forma_pago,metodo_pago,total,subtotal_productos,costo_envio,departamento_entrega,municipio_entrega,zona_entrega,saldo_pendiente,canal_origen,conversacion_id,responsable_id,observaciones,vendedor,requiere_envio,entrega_mensajero,creado_por,codigo) values(v_cliente_id,trim(p_datos->>'cliente'),nullif(trim(p_datos->>'telefono'),''),case when v_requiere_envio then trim(p_datos->>'direccion') else null end,nullif(p_datos->>'fecha_pedido','')::date,nullif(p_datos->>'fecha_entrega','')::date,coalesce(nullif(trim(p_datos->>'estado'),''),'Pendiente'),v_estado_pago,v_estado_pago,coalesce(nullif(trim(p_datos->>'forma_pago'),''),'Efectivo'),coalesce(nullif(trim(p_datos->>'forma_pago'),''),'Efectivo'),v_total,v_subtotal,case when v_requiere_envio then v_costo_envio else 0 end,case when v_requiere_envio then nullif(trim(p_datos->>'departamento_entrega'),'') end,case when v_requiere_envio then nullif(trim(p_datos->>'municipio_entrega'),'') end,case when v_requiere_envio then nullif(trim(p_datos->>'zona_entrega'),'') end,v_total-v_abono,coalesce(nullif(trim(p_datos->>'canal_origen'),''),'Manual'),nullif(p_datos->>'conversacion_id','')::uuid,nullif(p_datos->>'responsable_id','')::uuid,nullif(trim(p_datos->>'observaciones'),''),nullif(trim(p_datos->>'vendedor'),''),v_requiere_envio,v_entrega_mensajero,v_usuario,'') returning id, numero_pedido into v_pedido_id, v_numero;
  v_codigo := 'PED-' || lpad(v_numero::text,4,'0'); update public.pedidos set codigo=v_codigo where id=v_pedido_id;
  for v_item in select value from jsonb_array_elements(p_datos->'items') loop select * into v_producto from public.productos where id=(v_item->>'id')::uuid; insert into public.pedido_detalle(pedido_id,producto_id,cantidad,precio,costo) values(v_pedido_id,v_producto.id,(v_item->>'cantidad')::numeric,coalesce((v_item->>'precio')::numeric,v_producto.precio_venta),coalesce((v_item->>'costo')::numeric,v_producto.costo,0)); end loop;
  if v_abono > 0 then insert into public.pagos(pedido_id,cliente_id,monto,metodo,fecha) values(v_pedido_id,v_cliente_id,v_abono,coalesce(nullif(trim(p_datos->>'forma_pago'),''),'Efectivo'),current_date); end if;
  if v_requiere_envio and coalesce((p_datos->>'guardar_direccion')::boolean,true) then select id into v_direccion_id from public.cliente_direcciones where cliente_id=v_cliente_id and direccion=trim(p_datos->>'direccion') and coalesce(departamento,'')=coalesce(nullif(trim(p_datos->>'departamento_entrega'),''),'') and coalesce(municipio,'')=coalesce(nullif(trim(p_datos->>'municipio_entrega'),''),'') and coalesce(zona,'')=coalesce(nullif(trim(p_datos->>'zona_entrega'),''),'') order by principal desc, created_at desc limit 1; if v_direccion_id is null then insert into public.cliente_direcciones(cliente_id,etiqueta,direccion,departamento,municipio,zona,principal,ultima_entrega_at,veces_usada) values(v_cliente_id,'Dirección de entrega',trim(p_datos->>'direccion'),nullif(trim(p_datos->>'departamento_entrega'),''),nullif(trim(p_datos->>'municipio_entrega'),''),nullif(trim(p_datos->>'zona_entrega'),''),not exists(select 1 from public.cliente_direcciones where cliente_id=v_cliente_id),now(),1); else update public.cliente_direcciones set ultima_entrega_at=now(), veces_usada=veces_usada+1 where id=v_direccion_id; end if; end if;
  if nullif(p_datos->>'cotizacion_id','') is not null then update public.cotizaciones set estado='Convertida', convertido_pedido_id=v_pedido_id where id=(p_datos->>'cotizacion_id')::uuid; end if;
  return jsonb_build_object('pedido_id',v_pedido_id,'cliente_id',v_cliente_id,'codigo',v_codigo,'total',v_total,'saldo_pendiente',v_total-v_abono,'pago_estado',v_estado_pago);
end;
$$;

create or replace function private.editar_pedido_y_detalle_seguro(p_datos jsonb)
returns jsonb language plpgsql security definer set search_path = public, private as $$
declare
  v_usuario uuid := (select auth.uid()); v_pedido public.pedidos; v_subtotal numeric(14,2); v_total numeric(14,2); v_pagado numeric(14,2); v_actualizar_lineas boolean := coalesce(jsonb_typeof(p_datos->'lineas') = 'array', false); v_linea jsonb; v_producto public.productos; v_cantidad integer; v_requiere_envio boolean;
begin
  if v_usuario is null or not private.tiene_modulo_crm('pedidos') then raise exception 'No autorizado para editar pedidos'; end if;
  select * into v_pedido from public.pedidos where id = nullif(p_datos->>'pedido_id', '')::uuid for update; if not found then raise exception 'Pedido no disponible'; end if; if v_pedido.estado = 'Cancelado' then raise exception 'No puedes editar un pedido cancelado'; end if; if exists (select 1 from public.facturas where pedido_id = v_pedido.id) then raise exception 'No puedes modificar un pedido que ya tiene una factura FEL'; end if;
  if v_actualizar_lineas then if v_pedido.estado <> 'Pendiente' then raise exception 'Los productos solo se pueden modificar mientras el pedido esté Pendiente. Si ya inició producción, crea un ajuste controlado.'; end if; if jsonb_array_length(p_datos->'lineas') = 0 then raise exception 'El pedido debe tener al menos un producto'; end if; for v_linea in select value from jsonb_array_elements(p_datos->'lineas') loop v_cantidad := nullif(v_linea->>'cantidad', '')::integer; if v_cantidad is null or v_cantidad < 1 then raise exception 'Cada producto debe tener una cantidad de al menos 1'; end if; select * into v_producto from public.productos where id = nullif(v_linea->>'producto_id', '')::uuid and coalesce(estado, 'Activo') = 'Activo'; if not found then raise exception 'Uno de los productos seleccionados ya no está disponible'; end if; end loop; delete from public.pedido_detalle where pedido_id = v_pedido.id; insert into public.pedido_detalle(pedido_id, producto_id, cantidad, precio, costo) select v_pedido.id, (value->>'producto_id')::uuid, (value->>'cantidad')::integer, producto.precio_venta, producto.costo from jsonb_array_elements(p_datos->'lineas') join public.productos producto on producto.id = (value->>'producto_id')::uuid; select coalesce(sum(cantidad * precio), 0) into v_subtotal from public.pedido_detalle where pedido_id = v_pedido.id; else v_subtotal := coalesce(v_pedido.subtotal_productos, v_pedido.total - coalesce(v_pedido.costo_envio, 0)); end if;
  v_total := v_subtotal + greatest(coalesce(nullif(p_datos->>'costo_envio', '')::numeric, v_pedido.costo_envio, 0), 0); select coalesce(sum(monto), 0) into v_pagado from public.pagos where pedido_id = v_pedido.id; if v_total < v_pagado then raise exception 'El total no puede ser menor a los pagos ya registrados'; end if; v_requiere_envio := coalesce(v_pedido.requiere_envio, false);
  update public.pedidos set forma_pago = coalesce(nullif(trim(p_datos->>'forma_pago'), ''), forma_pago), fecha_entrega = coalesce(nullif(p_datos->>'fecha_entrega', '')::date, fecha_entrega), hora_entrega = coalesce(nullif(trim(p_datos->>'hora_entrega'), ''), hora_entrega), direccion = nullif(trim(coalesce(p_datos->>'direccion', direccion)), ''), departamento_entrega = nullif(trim(coalesce(p_datos->>'departamento_entrega', departamento_entrega)), ''), municipio_entrega = nullif(trim(coalesce(p_datos->>'municipio_entrega', municipio_entrega)), ''), zona_entrega = nullif(trim(coalesce(p_datos->>'zona_entrega', zona_entrega)), ''), observaciones = nullif(trim(coalesce(p_datos->>'observaciones', observaciones)), ''), vendedor = nullif(trim(coalesce(p_datos->>'vendedor', vendedor)), ''), canal_origen = coalesce(nullif(trim(p_datos->>'canal_origen'), ''), canal_origen, 'Manual'), entrega_mensajero = v_requiere_envio and coalesce(nullif(trim(p_datos->>'entrega_mensajero'), '')::boolean, entrega_mensajero, false), subtotal_productos = v_subtotal, costo_envio = greatest(coalesce(nullif(p_datos->>'costo_envio', '')::numeric, costo_envio, 0), 0), total = v_total, saldo_pendiente = greatest(0, v_total - v_pagado) where id = v_pedido.id;
  return jsonb_build_object('pedido_id', v_pedido.id, 'subtotal', v_subtotal, 'total', v_total, 'saldo', greatest(0, v_total - v_pagado));
end;
$$;
